package examplefuncsplayer.fast;

import battlecode.common.*;
import MPWorking.Debug;

public class FastSort {

    public static RobotController rc;

    public static void init(RobotController r) {
        rc = r;
    }

    // public static void main(String[] args) {
    //     int[] a = new int[]{4, 2, 3, 5, 0, 15, 20};
    //     sort(a);
    //     for(int i = 0; i < FastSort.size; i++) {
    //         System.out.println("" + i + ": " + a[FastSort.indices[i]] + "\n");
    //     }
    // }

    // DISTANCE SORT


    // Sorts array in increasing order, placing the indices of the sorted array in indices
    // See the commented out main method for an example of how to use this class
    // WARNING: Only sorts arrays of nonnegative integers
    // WARNING: If the array has more than 16 elements, only the first 16 will be sorted.
    // MAIN SORT

    // VARS

    // SORTING NETWORKS

}
