# Credit to Producing Perfection (https://github.com/awesomelemonade/Battlecode2022)
name: Run Matches
on: [workflow_dispatch, pull_request]
concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  test_private_action_job:
    name: Run Matches
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v3
      # run python/java to play against precompiled programs - pipe results to file
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Download JDK 8
        run: curl https://transfer.sh/BVevnp/jdk-8u361-linux-x64.tar.gz -o jdk-8u361-linux-x64.tar.gz
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: jdk-8u361-linux-x64.tar.gz
          java-version: '8.0.361'
          architecture: x64
      - name: Java Version
        run: java -version
      - name: Make Executable
        run: chmod +x gradlew
      - name: Gradle Update
        run: ./gradlew update
      - name: Build with Gradle
        run: ./gradlew build
      - name: List Tasks
        run: ./gradlew tasks
      - name: Run Match
        run: python run_matches.py
      # upload match files as artifact
      - name: Archive Match Files
        uses: actions/upload-artifact@v2
        with:
          name: matches
          path: matches
          retention-days: 90
      # upload summary as artifact
      - name: Archive Summary
        uses: actions/upload-artifact@v2
        with:
          name: matches-summary${{ github.run_number }}
          path: matches-summary${{ github.run_number }}.txt
          retention-days: 90
      # send summary to repo
      - name: Add Match Summary
        run: git add matches-summary${{ github.run_number }}.txt
      - name: Commit Match Summary
        run: git commit -m "Match Summary for Workflow Run (#${{ github.run_number }})"
      - name: Push Match Summary
        run: git push origin HEAD:master